title=Boller i karry
date=2024-10-03
type=page
tags=bage
status=published
category=gris
~~~~~~
= Boller i karry

== Ingredienser

=== Kødboller

800 g hakket kalv og flæsk

50 g løg finthakket

150 g squash fintrevet og drænet for vand

2 æg

2 tsk loppefrøskaller

2 tsk salt

friskkværnet peber

1,5 liter kyllingebouillon/hønsebouillon eller grøntsagsbouillon

=== Karrysovs

50 g løg finthakket

80 g æble skrællet og fintrevet (kan udelades men giver virkelig god smag)

2 spsk karry mere eller mindre alt efter styrke

5 dl kogefond altså væsken, kødbollerne har kogt i

5 dl fløde

100 g flødeost naturel

0,5 spsk salt

smør eller kokosolie til stegning


== Fremgangsmåde

=== Kødboller

Rør farsen og form kødbollerne i den ønskede størrelse.

Opvarm bouillon til kogepunktet i en suppegryde og nedsænk kødbollerne heri, så det passer med at alle kødboller kan nå op til overfladen. Det passer cirka med halvdelen af gangen

Lad kødbollerne koge i 7-8 minutter og fisk dem så op med en hulsi og sæt dem til side. Gem kogefonden.

=== Karrysovs

Opvarm kokosolie i bunden af en sauterpande eller en gryde og sauter løg, æble og karrypulver heri.

Hæld kogefond og fløde og salt i og kog op. Lad simre, så sovsen tykner. Gerne i 15 minutter.

Rør flødeosten ud i, så sovsen bliver endnu mere cremet.

Smag til med salt. Når sovsen har den rette smag, hælder du kødbollerne herover og lader dem hygge sig i sovsen, imens du dækker bordet.