title=Rugbrød
date=2024-10-03
type=page
tags=bage
status=published
category=bage
~~~~~~
= Rugbrød

== Ingredienser

 * 300 gram surdej fra køleskabet

 * 6,5 dl koldt vand

 * ca 22 g salt

 * 200 g rugkerner

 * 50 g andre kerner; solsikke, græskar...

 * 550 g rugmel (Hvis ekstra kerner droppes skal der 600 g rugmel i)

== Fremgangsmåde

Surdej og salt røres ud i vandet i stor skål eller røremaskine.

Kerner tilsættes og tilsidst mel.

Rører godt sammen.

Tag 300 g surdej fra og sæt i køleskab.

Dejen hældes op i en form (vores er 18 cm lang og 10 høj så vi får et stort stykke rugbrød).

Hæver ca 7 til 7, 5 timer. Hvis det hæver så længe, at dejlen vælter ud over kanten og over det hele, vil 
brødet falde sammen på midten. Jeg sætter altid vores i ovnen på en bageplade, så kan den stå og hygge
 der :-)

Bages ved 100 grader i 1 time, der skrues op til 200 grader og det bages videre i 1 time og 5 minutter.
 Varmluft kan sagens bruges, så trækkes der lidt temperatur fra.

(Det er færdigbagt ved kerne temperatur på 98 grader ifølge svigerfar.)

Vi har brødet liggende på et skærebræt med viskestykke om de første par dage, inden det kommer i en 
plastikpose. Modsat lyst brød kan man ikke tage det ud kl 17.15 og regne med at spise det kl 17.30. Det
er ikke til at skære varmt og er en smule klægt.