title=Ande confit
date=2024-10-03
type=page
tags=bage
status=published
category=and
~~~~~~
= Ande confit

== Ingredienser

4 stk. andelår (over + underlår)

500 g andefedt

4-5 fed hvidløg

1-2 kviste frisk timian

1-2 kviste frisk rosmarin

2 stk. lauerbærblade

1 spsk. groft knuste peberkortn

1 spsk. sukker

2 spsk. salt

1 l andefedt (bestil hos slagteren)

== Fremgangsmåde

=== Confit de canard

Gnid andelårene grundigt ind i hvidløg. Hak de skyllede krydderurter. OBS: Det er meget vigtigt, at de friske krydderurter er helt rengjorte, og at der ikke er det mindste jord ved dem!

Drys lårene med krydderurter, salt, peber og sukker. Kom køkkenfilm over og lad stykkerne marinere natten over i køleskabet.

Dagen efter smeltes fedtet i en gryde, og andestykkerne kommes i efter at være børstet fri for salt og krydderier. De skal være helt dækkede af fedtet.

De koges forsigtigt i ca. 2½-3 timer, eller til de er meget møre. Det er meget vigtigt at fedtet ikke bliver for varmt, for stykkerne må ikke stege. Fedtet skal bare lige småboble.

Kom andestykkerne i en lertøjskrukke eller lign. og dæk dem med det siede fedt. Andeconfit'en kan holde sig i køleskab i omkring 6 måneder, og man kan bruge af det lidt efter lidt, blot de resterende stykker er dækkede af fedt.

Når de skal bruges, skrabes de fri af det meste af fedtet og kan så enten steges sprøde på en pande ved ikke for høj varme, eller de kan sættes i en 200 grader varm ovn til de er gyldne og sprøde. Vend dem undervejs.

Server dem med råstegte kartofler, der er stegt i noget af andefedtet og en god rødkålssalat.