title=Bøf Stroganoff
date=2024-10-03
type=page
tags=bage
status=published
category=okse
~~~~~~
= Bøf Stroganoff

800 g oksefilet

3-4 spsk. edelsüss paprika

3-4 løg

2 spsk. smør

300 g champignon

5-6 tykke skiver bacon

2 spsk. koncentreret tomatpure

½ l fløde

salt og peber


Kødet skæres i strimler på størrelse med en lillefinger og pudres ind i paprikaen. 3-4 løg hakkes og klares i smørret i en smedejernsgryde eller lignende. Når løgene er klare, fisker man dem op og sætter dem til side.

Bacon skåret i mindre strimler steges i gryden til de er gyldne, men ikke for sprøde. Så tages de op og sættes også til side.

Champignonerne renses og skæres i tynde skiver og steges på en separat pande i lidt smør. Sæt dem ligeledes til side.

I det fedt, der er tilbage i gryden, brunes nu kødstrimlerne over en rask ild. Hvis der ikke er nok fedt, må der tilsættes lidt olie. Men pas på - paprika er slemt til at brænde på, så der skal røres.

Når kødet begynder at blive lidt fast i konsistensen, tilsættes et par skefulde koncentreret tomatpuré og bruner med. Fløden kommes ved og får et kort opkog, hvorpå man tilsætter løg, bacon og de ristede champignons.

Og så skal Stroganoff'en bare varmes hurtigt igennem, smages til med salt og peber og serveres rygende varm.